<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="KurrentDB.Client" Version="1.2.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.6.0" />
    <PackageVersion Include="Microsoft.Orleans.Dashboard" Version="10.1.0" />
    <PackageVersion Include="Microsoft.Orleans.EventSourcing" Version="10.1.0" />
    <PackageVersion Include="Microsoft.Orleans.Sdk" Version="10.1.0" />
    <PackageVersion Include="Microsoft.Orleans.Reminders" Version="10.1.0" />
    <PackageVersion Include="Microsoft.Orleans.Server" Version="10.1.0" />
    <PackageVersion Include="Microsoft.Orleans.Client" Version="10.1.0" />
    <PackageVersion Include="Microsoft.Orleans.TestingHost" Version="10.1.0" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.3" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.401" />
    <PackageVersion Include="Microsoft.Build.Tasks.Git" Version="10.0.401" />
    <PackageVersion Include="MinVer" Version="7.0.0" />
    <PackageVersion Include="xunit.v3" Version="3.2.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageVersion Include="OpenTelemetry.Api" Version="1.15.3" />
  </ItemGroup>
</Project>